_commit: "dfd5cbcd5e2d1c635e47224593d21aa19e2c1a76"
_src_path: https://github.com/alexym1/copier-template.git
email: "yahiaoui-martinez.alex@outlook.com"
full_name: "Alex MARTINEZ"
github_username: "Taglyatelle/taglyatelle"
language: "uv"
project_name: "taglyatelle"
project_short_description: "Delegate tasks to your AI agent on multiple Git hosting services"
project_slug: "taglyatelle"
repo_visibility: "public"
