name: 'Check code quality'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pipx uv
        python3 -m pipx install prek
    
    - name: Install project dependencies
      shell: bash
      run: |
        uv sync --all-extras
    
    - name: Run pre-commit checks
      shell: bash
      run: |
        prek install --config config/pre-commit/.pre-commit-config.yaml
        prek run --config config/pre-commit/.pre-commit-config.yaml --all-files
