name: Checks PR to master/main

on:
  pull_request:
    branches: [ master, main ]

jobs:
  checks-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Check code quality
        uses: ./.github/actions/check-code-quality

  test:
    strategy:
      matrix:
        python-versions: 
        - "3.12"
        os: 
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: false
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv sync --all-extras
      - name: Run tests
        run: |
          uv run pytest -c "config/tests/setup.cfg"
